CREATE TABLE [Orders] ( 
	[OrderID] INTEGER  NOT NULL PRIMARY KEY, 
	[VendorID] INTEGER  NOT NULL,
  [SKU] INTEGER  NOT NULL,
	[Quantity] INTEGER  NOT NULL,
  FOREIGN KEY (SKU) REFERENCES Inventory
); 

INSERT INTO Orders VALUES(1, 65, 10, 50);
